import Footer from "./components/Footer"
import Header from "./components/Header"
import "./global.css"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="cupcake">
      <body>
        <Header />
        <main className="container mx-auto p-10">
          {children}
        </main>
        <Footer />        
        </body>        
    </html>
  )
}
